### PR TITLE
Made Klaro work in IE11

### PR DESCRIPTION
**Pull request by Meidor**
I've made some small changes in Klaro to make it work in IE11.
For this I've introduced some new dependencies:

- [Babel-plugin-transform-runtime](https://babeljs.io/docs/en/6.26.3/babel-plugin-transform-runtime): to polyfill ES6 features only where it is needed (this works together witht the babel-runtime dependency)
- [currentExecutingScript](https://github.com/JamesMGreene/currentExecutingScript): to stand in for document.currentExecutingScript in IE11 which doesn't have this function

I've also removed node_modules from the webpack babel-loader config because node modules are alreade ES5 and don't need to be transpiled (the code also didn't compile with this included + babel-plugin-transform-runtime) and changed the setter of style to style.cssText for better compatibility.

### CODE REVIEW

**Comment by adewes** [comment]
Thanks @Meidor , I'll need to check this a bit more carefully, so it might take a bit to merge this as I'm currently very busy.

**Comment by Meidor** [comment]
No problem at all @adewes, I understand that you have to check this more carefully!

**Comment by vinitkumar** [comment]
@adewes Please merge this?

**Comment by adewes** [comment]
Thanks @Meidor! @vinitkumar, sorry for the delay in merging this. Please report any issues you encounter.

**Pull request merged**
