### PR TITLE
Possibility to accept all cookies and hide decline in notice

### PR DESCRIPTION
**Pull request by DalbertHab**
Added option to accept all cookies at once.
Added option to replace "decline all" with open modal.
Added privacy policy link to notice

### CODE REVIEW

**Comment by DalbertHab** [comment]
Dear Jaller,

the EuGH (az. c-673/17) decided that all cookie have to be opt-in cookies. So `default: true` for all apps is no option. The current implementation let you gather no cookie acceptance as no one customizes it's cookie experience. Everyone clicks on "ok" or "accept". If you offer a "decline" option there is no difference in result (`default: false` for all apps).

As a site owner you want to have cookie acceptance for statistics and advertising. Therefore the "accept-all"-Option will help to gather the opt-in.

## Privacy Policy

I added an option to show/hide the pricy policy link in the notice.

**Comment by matjaeck** [comment]
> the EuGH (az. c-673/17) decided that all cookie have to be opt-in cookies

That's incorrect in two ways:

- not the court decided this, but Directive 2009/136/EG changed article 5 (3) of directive 2002/22/EG  to require consent. The court just based its decision on this long existing law.
- Required cookies can still be set without obtaining consent.

The decision you're quoting was more about under which conditions valid consent can be obtained (no pre-checked checkboxes).

**Comment by DalbertHab** [comment]
I just wanted to clarify that an opt-in is necessary for almost all cookies. Therefore **default** should be set to **false** in the config. With this setting, however, no cookies are set in the current version and therefore no advertising, tracking or similar is possible. And if you are a website owner you want advertising and tracking.

**Comment by gebeer** [comment]
+1 Please implement this, at least as an option. Thank you.

**Comment by adewes** [comment]
I'll have a look at this now.

**Comment by adewes** [comment]
Ok, so looking at this I also don't see why you can't simply set `default: true` in your config (which will enable all trackers / apps by default) and customize the `Accept` button text to say `Accept all`?  Since there is a config option that will always allow necessary cookies those will still be enabled.

Through a separate PR we also have a `Learn More` button now.

Can you let me know what is missing in terms of functionality here for your use case? In principle I agree with @jaller94 in that we want to keep Klaro as simple as possible, so if a desired behavior can be realized with small changes in the configuration using existing options I would prefer that solution. I'm open to consider changes if they are really not implementable with the current feature set though, and I think the "Accept All" use case you propose is valid.

**Comment by gebeer** [comment]
> Ok, so looking at this I also don't see why you can't simply set `default: true` in your config (which will enable all trackers / apps by default) and customize the `Accept` button text to say `Accept all`? Since there is a config option that will always allow necessary cookies those will still be enabled.

The problem is, that most users just click ok. Then scripts like analytics will still be disabled. Because they have to be set to `default:false` Otherwise it would violate the law. With "Accept all" we could get consent even from the majority of users that just click the green button to get the annoying message out of the way.

**Comment by gebeer** [comment]
> so if a desired behavior can be realized with small changes in the configuration using existing options I would prefer that solution.

The desired behaviour cannot be achieved by changing existing config options. Because scripts like analytics are not allowed to run on first page load. 
If I set them to `default:true`, they will fire at 1st page load, right?

**Comment by adewes** [comment]
OK, I think I understand your use case now (sorry I deleted my last comment that you commented). I have seen this or similar workflows on several websites (e.g. lufthansa.com) and I think it's delicate to implement because it might be considered as a "dark pattern", so I want to make sure we implement this in a way that is obvious to the user.

My take on this is the following:

* Which flow you need to implement depends strongly on your legislation. In the EU for example there's a mix of requirements from the ePrivacy directive (which is implemented differently in each EU country), the GDPR and possible additional regional legislations, such as the TMG (Telemediengesetz) in Germany. So with Klaro we want to accomodate as many of these flows as possible.
* Regardless of the legislatory framework, I think it should be obvious for the user which choices he made. There should be nothing surprising or misleading about the consent process.

According to your proposal, the workflow would be like this:

* Cookie notice pops up.
* Option A: The user clicks on "Accept all" and accepts all trackers / apps. Notice disappears.
* Option B: The user clicks on "Learn more" and can customize his choice. He can then click on "Save" and the chosen apps / trackers will be enabled. Notice disappears.

In that scenario, the user would have no way to decline cookies, which is not very user-friendly.

I think the workflow you want to implement is already supported by Klaro by simply setting `default: true`. Please note that setting `default: true` will *NOT* load the app before the user consents (there is an `optOut` option that does this, but whose use we strongly discourage).

Are you really sure this isn't the flow you intend to implement?

**Comment by gebeer** [comment]
> I think the workflow you want to implement is already supported by Klaro by simply setting `default: true`. Please note that setting `default: true` will _NOT_ load the app before the user consents (there is an `optOut` option that does this, but whose use we strongly discourage).
> 
> Are you really sure this isn't the flow you intend to implement?

Thank you very much for clarifying. I just edited my previous post after realising that scripts will not fire on first page load.
And I agree that the Decline all button should be there.
I will follow your recommendation for the setup and just change the wording of the OK-Button to "Accept all".
Thanks for this tool and keep up the great work!

**Comment by adewes** [comment]
Cool, glad this resolves your issue! I think it's the cleanest way to implement this as it's not surprising to the user, doesn't use any dark patterns and still gives the user a choice to only accept functional cookies.

I will close this PR then (thanks in any case for your work and input!), if you have another problem please open another issue.

**Comment by DalbertHab** [comment]
@adewes if you set `default: true` then the type of the option is an "opt-out-option. In Germany all options have to be "opt-in"-options, even Google Analytics.

"Option A" is to gather as many cookies as possible. (Not user friendly)
"Option B" allows the user to opt into the desired options and save his choice if he clicks on "save" instead of "accept all" (Dark pattern).

I respect your choice and will maintain the fork.

best regards
David

**Comment by adewes** [comment]
The user can opt out of all non-functional cookies by clicking the `Decline` button. As far as I am aware this is compliant to both GDPR and ePrivacy (https://europa.eu/youreurope/citizens/consumers/internet-telecoms/data-protection-online-privacy/index_en.htm), as it is a free `Yes/No` choice the user can take and the two options have the same prominence in the UI. It is not an opt-out solution because no apps or cookies are enabled/set before the user consents and the user has an obvious way to decline as well as change his consent. I agree that if we didn't have a `Decline` button it would be an opt-out solution because the user would need to manually toggle all apps and click on `Save`, that's exactly what `Decline` does though. Consent forms of companies like lufthansa.com work in the same way btw, I find their UI more misleading though since a click on the `Accept all` button will not honor the changes made above in the checkboxes and simply enable all of them (they of course designed this so that most people click on the `Accept all` button). I'm pretty confident their solution is compliant, so ours should be too. What's your opinion, do you find this more intuitive?

grafik


Maybe we could add more options to the modal, which I also find confusing though because we would need e.g. `Accept selection`, `Accept all` and `Decline all` buttons, which is even more confusing as they would undo some changes that the user might have made by toggling sliders (hence we decided to only have a `Save` button that persists the choice you made above). We could of course add a `Toggle all` slider that enables/disables all non-functionally required apps.

We can think about restructuring the preselection in the modal to give the user more fine-grained control over what trackers / apps should be enabled. I plan to also group apps by category to make switching them on/off more easy, as it can quickly get unwieldy with many apps.

**Comment by adewes** [comment]
I might change the modal so that we have `Accept selection` and `Decline` buttons if the user hasn't consented yet, this will make it more obvious that not consenting is still an option. I will also add a toggle button to turn on/off all apps at once. Like that, there are three different ways for the user to decline consent (click on `Decline` in the notice, toggle off all apps and click on `Accept selection` or click on `Decline` in the modal).

**Comment by adewes** [comment]
I made some changes and (hopefully) small improvements to this and merged it into master, will be released in 10 minutes. Thanks again @DalbertHab, if you have any remarks or feedback please open another PR or issue. I hope the UI is more clear now for users while providing a reasonable "Accept all" functionality.

I also added a delay and animation to clearly indicate to the user what happens when he/she clicks on "Accept all" or "Decline", I hope this will make it more apparent what the button does.

Since I added a new button we're missing some translation strings now. I will have to think about how we can make translations more scalable, as we have so many languages it become quite difficult to even change small UI elements without breaking most translations.

**Comment by sebastiancx** [comment]
@adewes Would it be possible to include an option like the one in your screen above? Say: The user has the possibility to accept only necessary ones and not only all or decline? Or is decline this option but naming differently? Cause this option to accept only necessary is in the modal but not in the consentNotice.

**Comment by adewes** [comment]
Hi @sebastiancx! In fact necessary cookies/apps will always remain enabled (as the site won't function without them). Maybe we should indeed name that differently to make this more clear. You can easily override the default translation in your config BTW, I'll see how we can update this in general.

We're working on a better strategy to manage  Klaro translations, as we have more than 20 languages now consistently changing or adding translations becomes quite challenging...

**Comment by sebastiancx** [comment]
Thanks for the quick answer @adewes!
I agree with you, the naming seems very confusing.
Renaming it would not be the problem. But if I rename it e.g. to "Nur notwendige akzeptieren", it would be duplicated in the modal. Is it possible to remove the `Decline` button in the modal but not for the notice?

grafik

**Comment by sebastiancx** [comment]
Wait. My bad. I mislabeled the button in the screenshot above. Should be fine now.

**Comment by adewes** [comment]
Ok, great. The behavior of the modal reflects that of the notice so that it's not surprising to the user. Once a user has made a choice, there will be only a save button in the modal.

**Pull request merged**
