### PR TITLE
Added Italian and Romanian translation

### PR DESCRIPTION
**Pull request by anatolinicolae**
Contributing to i18n as per issue #1.

### CODE REVIEW

**Comment by adewes** [comment]
Thanks for this @anatolinicolae! Could you merge master with your branch and add the new translations as well (we just added a few more)? That would be really awesome :)

**Comment by anatolinicolae** [comment]
😔I've already did that after the french pull merge... Will do one more later today...

**Comment by anatolinicolae** [comment]
Lemme know should it require further fixes. I think I didn't miss anything in the translations' merge, but another check would be welcome :)

**Comment by adewes** [comment]
Great, thanks again @anatolinicolae !

**Pull request merged**
