### PR TITLE
Add cross-env support

### PR DESCRIPTION
**Pull request by BhaveshSGupta**
To make build possible even on windows.

### CODE REVIEW

**Comment by jaller94** [comment]
This works for you?
I thought lines with multiple variables and commands need one `cross-env-shell` at the start of the line instead of multiple `cross-env`.
https://www.npmjs.com/package/cross-env#cross-env-vs-cross-env-shell

Don't have a Windows to test this though. If you say this works, it can get merged.

**Comment by BhaveshSGupta** [comment]
cross-env works fine,
Although I had checked only make-dev and make-watch. But I found make is giving error at APP_VERSION=`git tag --points-at HEAD` saying tag is not defined.

**Comment by jaller94** [comment]
Without a tag on the currently checked out HEAD, the command should not output a string.

**Comment by jaller94** [comment]
I don't see a way to edit your branch so I "forked" your PR to #89.

**Comment by BhaveshSGupta** [comment]
@jaller94 This issue is now fixed as per my new commits, can you review them.

**Comment by jaller94** [comment]
Fixes #95.

**Comment by jaller94** [comment]
For every release after v0.2.11 Windows users will have to [set their NPM shell to power-shell](https://github.com/kentcdodds/cross-env/issues/192#issuecomment-513341729).
We start using string substitution to fix issue #131.

Further information:
https://www.npmjs.com/package/cross-env#windows-issues

**Pull request merged**
