### PR TITLE
Don't show apps as active if they are actually not (opened from notice)

### PR DESCRIPTION
**Pull request by leonexcc**
If you currently open the "Learn more..." button before the klaro cookie was set, the apps that are marked default = true will be already activated. First i think this is not a real Opt-In. Secondly i think this could give the impression that the app is already active (which is obviously not true).

In this pull request i changed the code so it will activate the apps if you click on "Ok" in the notice window. But it will show the apps disabled if you click on "Learn more..."

### CODE REVIEW

**Comment by jaller94** [comment]
I've had a first look at this and the team is in favour of merging this.
Hope to find time for the code review and testing soon.

**Comment by thomasaull** [comment]
Is this going to get anywhere soon? :)

**Comment by adewes** [comment]
Yes I'll have a look at it today or tomorrow, thanks for you patience :)

**Comment by thomasaull** [comment]
Awesome, thanks @adewes :)

**Comment by matjaeck** [comment]
> If you currently open the "Learn more..." button before the klaro cookie was set, the apps that are marked default = true will be already activated. First i think this is not a real Opt-In. Secondly i think this could give the impression that the app is already active (which is obviously not true).

The configuration parameters can indeed be a bit confusing (`default` vs. `optOut`) but assuming that an app is enabled by default (it loads before any consent was given), it is an Opt-Out service by definition. So this is indeed not an Opt-In.

Opt-Out works on `master` by setting the apps `default` parameter to `true`, and the `optOut` parameter to true, too. The apps will load when the page is loaded, as they should. If you want the app to be Opt-In only, then you'll need to set both parameters to false.

Note: I tested this with the global `default` paramter set to `false`.

So the first point of your issue might actually be caused by a wrong configuration or I misunderstand the problem.

The actual issue here is that when you change the setting in the modal but don't confirm it by clicking "Save" but either click on the close button or somewhere outside the modal so that it closes, the state is saved but not applied (e.g. it shows Matomo as activated but in fact it is not, see DevTools). This is even more a problem for Opt-Out apps, as the modal says they are disabled but are not. This issue is not solved by this PR.

What this PR does, is that an app with `default: true` and `optOut: true` will **not** load on loading the page anymore -- likely breaking existing configurations. 

I'd be careful with this since it is not clear to me what this PR actually fixes...

**Comment by danielzellfelder** [comment]
@matjaeck In my opinion the core of the problem is not the functionality but the design. For some users clicking on "Learn more…" (and neither ok or decline before) it may seem as if the "default: true" cookies were already enabled although they didn't click accept and it is an optIn-consent (ensured by global "default: false"). 

Technically it's working fine but the design possibly can confuse some users - only in the "Learn more"-modal. 

So at least in this case (default: true for individual apps and global default: false, to create a "one-click"-opt-in) the PR should fix the issue, right? Or do I misunderstand the PR?

But maybe another solution could be to differentiate somehow between the current state of a cookie / app and the marker for which cookies will be activated by clicking on save. 

How do you think about this?

**Comment by adewes** [comment]
Hey @danielzellfelder, sorry this takes a bit time, Klaro is currently only a "pro bono" side project for us. So, I think I understand your point. I think the `optOut` option (which we strongly discourage to use as it's not compliant under many legislations) can cause some confusion. We could show those options in a different color or indicate somehow that they are already enabled.

Can you explain your motivation for this PR again? Given your description I think you can implement the desired workflow with the existing options:

* If you chose `default: false` for all apps, none of them will be selected by default, so the user needs to opt in to each of them individually to enable them. This is the most privacy-friendly approach of course but goes beyond the GDPR / ePrivacy requirements.
* If you chose `default:  true` for all apps, all of them will be selected by default, so when the user clicks on `Accept`, they will all be enabled. However, the user can also click on `Decline` to accept only functional cookies. He can also click on `Learn more` to customize the apps that he wants to allow. This is (in our view) compliant with ePrivacy & GDPR since the user has a free choice to decline non-functional cookies and can also customize cookies if he wants.

Under normal circumstances you should not use `optOut: true` as it really isn't compliant with most legislations, the option only exists for people that are in a legislation where this might be required, and for cases where you want for technical reasons to preload an app that will not immediately set any cookies when it is loaded but needs to be present during the page load process to e.g. perform some local data collection, but which the user might still disable via Klaro.

**Comment by leonexcc** [comment]
The idea behind this merge request was:

> If you currently open the "Learn more..." button before the klaro cookie was set, the apps that are marked default = true will be already activated. First i think this is not a real Opt-In. Secondly i think this could give the impression that the app is already active (which is obviously not true).
>
> In this pull request i changed the code so it will activate the apps if you click on "Ok" in the notice window. But it will show the apps disabled if you click on "Learn more..."

In my opinion a preselected checkbox is not an opt in. This of course the worst case for website owners, since the can't trick the user easily to activate tracking. But i fear this was the whole idea behind the GDPR (btw. the ePrivacy is not finished yet).

The ```optOut: true``` does something different since it activates the apps immediately.

**Comment by adewes** [comment]
I see. What is considered an opt-in or opt-out depends on the choices that a user can make. The problem with pre-ticked checkboxes is that they usually occur in a form where there's only a single "submit" button that you can press to go forward.

With Klaro you have three choices though, you can accept the default settings (i.e. give your consent), decline your consent, or customize your choice before consenting. This is not an opt-out because none of the apps gets activated before the user gives his consent, which is compliant with ePrivacy and GDPR. These regulations also do not require the user to give his consent for each specific app individually, which would be unrealistic anyway for most websites because they use many third-party apps.

As you said, the proposed solution would lead to most users leaving all apps disabled, which might be great for privacy but is usually not acceptable to the website owner, as they usually have a good reason for including these third-party apps and disabling them by default will hurt the user experience on the website (e.g. missing webfonts or external resources). That's why I don't want to make this the default, as it would make Klaro useless for most website owners. If you as a website owner want to explicitly ask the user to turn on every app individually you can still do it by setting `default: false`.

I agree that the UI can still be improved, I will think about how we can do this, I really appreciate your input on this.

**Comment by leonexcc** [comment]
I do understand the case with webfonts. The problem for me is, if i use the ```default: false``` it will not get activated with "Accept all". Maybe we could instead make an option ```acceptAll: true``` that could be used if the visitor clicks "Accept all" to activate apps that are marked ```default: false```.

Maybe it would also be possible to show the preselected but NOT currently active apps in a different color. After clicking "Save" they would show als realy active.

**Comment by adewes** [comment]
So why don't you chose `default: true`? After all, you want to ask the user for permission to use all the listed apps on your website. I simply don't see what's wrong with that? Personally I find a solution that shows only the functional apps as enabled, but then enables **all** apps if the user clicks on `Accept all` more misleading than a solution that just plainly shows the apps for which you ask for permission and lets the user either decline that entirely, accept it entirely or customize his consent for specific apps.

**Comment by leonexcc** [comment]
It's ok. Every one has a different view on this whole topic and this pull request is old anyway.

**Pull request closed without merging**
