### PR TITLE
Better accessibility

### PR DESCRIPTION
**Pull request by Leimi**
Hi,

Here is some work to make the library globally more accessible, especially to people using screen readers.

The most notable change is the usage of React Modal, which requires some container div on the website Klaro is used.

### CODE REVIEW

**Comment by adewes** [comment]
Thanks for this @Leimi , looks really great! Merging in another PR with small style changes seems to have caused a conflict, would you be able to look at this and resolve it? I had a look but I'm not confident enough that I won't break any of your changes.

**Comment by Leimi** [comment]
Hey, thanks, will do :)

I hope it's OK to add React Modal in the mix. It's not that heavy, but it still adds a noticeable weight to the built JS. And it forces users more config with the `appElement`. I personnally think it's necessary, but this does not come without cost, so it's up to you in the end.

There are also a few things we could do to improve accessibility in the default styles provided. The default styles are "overridable" anyway, so it's not necessary, but it could be good to have already accessible defaults. I'll let you decide what you want. Here are the changes I would recommend:

- not using `px` for `font-size` and `line-height` properties, and instead use relative units. This allows user preferences (browser font size) to be taken into account.
- change colors so that every text has a minimum contrast ratio of 4.5:1 with its background, so that even people with low vision can read ([more info](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html)).

Just so you know, I already made those styling changes in my fork. Since I noticeably changed how CSS is authored, I didn't make a pull request. But feel free to check out my work if you are interested: https://github.com/empreinte-digitale/klaro/commit/aa5146dfa0af9dcc1aedd0d2927de75a7ee1db97, https://github.com/empreinte-digitale/klaro/commit/1f4a6736505a09a938ae7a1f392c61553763f307, https://github.com/empreinte-digitale/klaro/commit/b3a65491b2eb05e92e2ccf121d16ddf57e68e878, https://github.com/empreinte-digitale/klaro/commit/891cec5e32b31d8a512287a8ad4e34eb577e344e, https://github.com/empreinte-digitale/klaro/commit/af11ddbcae9ac2b00ad84f9c0e77709f8c4dad91

**Comment by Leimi** [comment]
Hey, I rebased the branch from master so that there is no conflict anymore.

**Comment by adewes** [comment]
Great, thanks @Leimi !

**Pull request merged**
