### PR TITLE
Support storing user preferences in localStorage

### PR DESCRIPTION
**Pull request by axelchalon**
Adds a new configuration item `klaroStorage`, defining how Klaro should store the user's consents. The value of `klaroStorage` can be either `'cookies'` (default) or `'localStorage'`.

### CODE REVIEW

**Comment by jaller94** [comment]
Thanks for your PR! What advantages are you getting out of the localStorage version?
Code looks good, but I wonder if it is safe to assume that the browser has localStorage support.
In comparison to cookies, this does not get send to the server, further strengthen the user's privacy. 👍

**Comment by axelchalon** [comment]
LocalStorage is not sent to the server and cannot be modified by the server (unless a malicious script is injected) — so the control over the choices stays 100% on the consumer side, and the server admins cannot even know what a particular customer's choices are.

**Comment by adewes** [comment]
Hi @axelchalon, thanks for the PR and sorry this took so long. This looks like a really good idea privacy-wise, I'll review and merge this soon.

**Comment by adewes** [comment]
Thanks again @axelchalon, great work! I just refactored it a bit and made sure it's backwards-compatible, will be released in the new version within 10 minutes.

**Comment by madeinffm** [comment]
Great Feature! As I understand correctly, the cookieExpires Property does not apply to localStorage, correct? So there is no way, that the localStorage "expires"?

Thanks!
Florian

**Comment by axelchalon** [comment]
> Great Feature! As I understand correctly, the cookieExpires Property does not apply to localStorage, correct? So there is no way, that the localStorage "expires"?
> 
> Thanks!
> Florian

Correct

**Pull request merged**
