### PR TITLE
Update translations.yml

### PR DESCRIPTION
**Pull request by ldbglobe**
Add French translations and update string order for better consistency

### CODE REVIEW

**Comment by anatolinicolae** [comment]
Most of these fixes are already applied in issue #3.

**Comment by adewes** [comment]
Sorry this caused a conflict due to a different merge, could you have a look at this @ldbglobe ? I think we will move each language translations to a separate file to make contributing and merge more easy, as soon as we have this merged I'll get started with that.

**Comment by anatolinicolae** [comment]
@adewes kinda sucks this way, good idea keeping translations separate! HMU if you need help with that.

**Comment by anatolinicolae** [comment]
@ldbglobe have a look at #16 and close this issue if the typos look good for you now.
@adewes I migrates the translations, keys looked fine to me but I'd love someone else to have a look again 🙌

**Comment by adewes** [comment]
It seems we have all new translations integrated with the new format now so I'm going to close this MR, I merged your two changes with the master manually. Thanks again @ldbglobe and @anatolinicolae for your work!

**Pull request closed without merging**
