### PR TITLE
Fix/Enhance some styling

### PR DESCRIPTION
**Pull request by Jako**
Fix a padding styling issue in the buttons
Add some additional variables for the buttons
Change the list description by a variable

### CODE REVIEW

**Comment by adewes** [comment]
And thanks again @Jako, very much appreciated!

**Comment by adewes** [comment]
Hey @Jako, I actually reverted some styling changes in master as e.g. the button text became quite low-contrast and the contrast of the "Decline" button was also quite low (which is not compliant). I'll take a look at the styling again though and see what we can integrate, so your contribution is still appreciated. If you want to use your styles on your own website (again, beware of low-contrast in the Decline button) you can use the non-CSS version of Klaro and simply modify the existing stylesheet.

**Comment by Jako** [comment]
Maybe I just forgot to change some fixed values to variables. It is quite important to make the button color changeable by a variable with a light theme. Then the color of the text would be dark and the text in the buttons too.

**Comment by adewes** [comment]
Ok I see, maybe something went wrong during the merge! I needed to make a release as there was also an important feature upgrade for a customer and a bugfix so I just reverted that change for now, I'll have a look at this again next week. Looks very nice btw, I always thought we need a light theme as well!

**Pull request merged**
