### PR TITLE
Fixed Spanish translation. Added Galician translation

### PR DESCRIPTION
**Pull request by jmalarcon**
The current Spanish translation has some problems. I've reviewed and updated it.

The ideal thing to do would be to create a "Spanish (Spain - International)" translation with a file `es-ES.yml`' and a general Spanish translation (for Latam) with `es.yml`. Would it be possible? In that case I'll take care of both files 😊

HTH

### CODE REVIEW

**Comment by jmalarcon** [comment]
I've added `gl.yml` for the translation to [Galician language](https://en.wikipedia.org/wiki/Galician_language).
It's used by around 3 million people in my country.

HTH

**Comment by jmalarcon** [comment]
The `pachake.json` file has some outdated references in de `devDependencies` section. One of them has an important security problem. It would be interesting to update them all. Webpack 5 is already available and maybe updating the project to use it would be a good thing to do too. 

I've not touched the file, but I can handle the update if you want.

Thanks for your great tool and work!

**Comment by adewes** [comment]
Hey @jmalarcon, that's awesome, thanks for your contribution! Yeah the Spanish translations were mostly auto-generated using DeepL, which is mostly good but has some issues, so we really appreciate your help with this :)

And yes regarding the package dependencies, we'll update those as well. Some of the security issues are not directly relevant to us (e.g. https://www.npmjs.com/advisories/1561), still it's good to update them regularly. A Webpack 5 upgrade might be good as well, we'll have a look at it (if you want to have a go at it we'd appreciate as well, of course)

**Comment by jmalarcon** [comment]
Thanks Andreas!

Any thoughts on the language variations such as "es" vs "es-ES"? I think it would be useful. For example, in Spanish for Spain sounds much more natural tu use the forms "tú" "vosotros" than the more formal "usted" "ustedes" (in English it's always "you" for both), so a "es-ES" for Spain would be different in that regard to the more general "es" for Spanish in other parts of the world.

I'll take a look at migration to Webpack 5.

Thanks.

**Comment by adewes** [comment]
Finally had the time to merge this, thanks again @jmalarcon! Regarding the language variations: Yes, that seems absolutely necessary! I think we can implement this without too much hassle, the browser already provides the language variations (which we disregard currently), we can change that code so that it first tries to find a full match for a given `[lang]-[variation]` combination and falls back to a `[lang]` translation if none is found.

**Comment by jmalarcon** [comment]
That would be perfect!

As soon as is done I'll update the Spanish translation to reflect the different ways to speak here in Spain and in Latam.

Thanks!

**Pull request merged**
